### PR TITLE
make tests work with iojs

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I'm holding off with merge until `0.19.0` has been released.

/cc @rvagg

**Comment by ralphtheninja** [comment]
Actually. I think I'll try to get a `leveldown@0.10.5` out tomorrow that includes an updated version of `nan` so we can get this baby running on `iojs@2.0.0`. Will squash afterwards.

**Comment by juliangruber** [comment]
> Actually. I think I'll try to get a leveldown@0.10.5 out tomorrow that includes an updated version of nan so we can get this baby running on iojs@2.0.0. Will squash afterwards.

+1

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/pull/170

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ level@0.19.1
```

**Pull request merged**
