### PR TITLE
chore: update level-packager and leveldown

### PR DESCRIPTION
**Pull request by achingbrain**
Updates dependencies to the latest versions and fixes linting errors flagged by the new version of standard.

### CODE REVIEW

**Comment by achingbrain** [comment]
This seemed like the next task on https://github.com/Level/community/issues/98 - hopefully it's helpful!

**Comment by vweevers** [comment]
Thanks but I was just working on that 😃

**Comment by vweevers** [comment]
https://github.com/Level/level/commit/53bd922979409efc6f1b715ff124bbed3aa7a334, https://github.com/Level/level/commit/d001b2c2f8367d49cb5e2c596384880b9e2ec860

**Comment by achingbrain** [comment]
Fair enough!

**Pull request closed without merging**
