### PR TITLE
types:  add abstract-level type dependence

### PR DESCRIPTION
**Pull request by eng-cc**
add `abstract-level` type dependence

### CODE REVIEW

**Comment by vweevers** [comment]
`abstract-level` is already present, as a transitive dependency.

**Comment by eng-cc** [comment]
> `abstract-level` is already present, as a transitive dependency.

Transitive dependencies can sometimes be problematic.

In patterns that avoid using transitive dependencies, it needs to be explicitly defined. 

such as pnpm

**Comment by vweevers** [comment]
I see.

Perhaps we can instead re-export `AbstractLevel` from the `classic-level` and/or `browser-level` packages? What is the more common pattern in the TS ecosystem?

**Comment by eng-cc** [comment]
> I see.
> 
> Perhaps we can instead re-export `AbstractLevel` from the `classic-level` and/or `browser-level` packages? What is the more common pattern in the TS ecosystem?

Re-export `AbstractLevel` from the `classic-level` or `browser-level` packages is also a nice solution.

But I think that re-export will lead to too many links of type export, which is not conducive to decoupling.

**Comment by vweevers** [comment]
Fixed in https://github.com/Level/level/pull/241 (added to `dependencies` instead of `devDependencies`).

**Pull request closed without merging**
