### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/level/issues/69

New minor or patch?

### CODE REVIEW

**Comment by vweevers** [comment]
> New minor or patch?

You're thinking minor because of the caret change? It's tricky this

**Comment by ralphtheninja** [comment]
> You're thinking minor because of the caret change? It's tricky this

Aye. We could always go back to `~` and release a patch to avoid this discussion :wink:

**Comment by ralphtheninja** [comment]
@juliangruber Hilfe bitte!

**Comment by juliangruber** [comment]
minor, even though we changed to `^`, it will still only expose minor changes to the consumer. We never publicly promised to keep the `~` for extra stability afaik.

**Comment by ralphtheninja** [comment]
2.1.0

**Pull request merged**
