### PR TITLE
fixes opencollective issue, not installing on docker and other architectures

### PR DESCRIPTION
**Pull request by mateodelnorte**
opencollective pulled a bit of a leftpad, which can be caught up on [here](https://github.com/opencollective/opencollective-cli/issues/3#issuecomment-378039208). This implements the recommended fix.

### CODE REVIEW

**Comment by vweevers** [comment]
I don't quite follow that thread. The bug never got an explanation?

**Comment by vweevers** [comment]
The [OP talks about 1.04 being broken](https://github.com/opencollective/opencollective-cli/issues/3#issue-262117612), which someone says makes `opencollective` the new leftpad (that would only be true if they unpublished), then [they actually did unpublish 1.0.4](https://github.com/opencollective/opencollective-cli/issues/3#issuecomment-333577821) (which is worse than having a broken version), and then later, they recommend to [update to 1.0.4 again](https://github.com/opencollective/opencollective-cli/issues/3#issuecomment-364948146)?

I'm sorry, I'm very confused 😕

**Comment by mateodelnorte** [comment]
They recommended changing the dependency from `opencollective` to `opencollective-postinstall`. The bug is that on some architectures, `opencollective` did not install – in this case causing level's install to fail. This was happening to me 100% of the time, when installing via docker. 

Here's what you actually see, when attempting to install: 
```
make install
docker-compose -f docker-compose.build.yml run --rm install
                                                           [..................] | rollbackFailedOptional: verb npm-session 9ae87c3139b3npm WARN notice [SECURITY] stringstream has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=stringstream&version=0.0.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] randomatic has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=randomatic&version=1.1.7 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=0.8.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] deep-extend has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=deep-extend&version=0.4.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! path /usr/src/[my project]/node_modules/opencollective/dist/bin/opencollective.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/src/[my project]/node_modules/opencollective/dist/bin/opencollective.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2018-05-22T21_56_36_176Z-debug.log
make: *** [install] Error 254
```

**Comment by vweevers** [comment]
And https://github.com/Level/level/pull/101 didn't fix it for you? Which landed in level 3.0.1.

**Comment by vweevers** [comment]
> The bug is that on some architectures, opencollective did not install – in this case causing level's install to fail. 

I don't like unexplained bugs :) But I'm fine with merging this.

> And #101 didn't fix it for you? Which landed in level 3.0.1.

If so: we'll do another patch release.

**Comment by ralphtheninja** [comment]
> They recommended changing the dependency from opencollective to opencollective-postinstall. The bug is that on some architectures, opencollective did not install – in this case causing level's install to fail. This was happening to me 100% of the time, when installing via docker.

Ugh :cry: 

Sorry about this.

**Comment by ralphtheninja** [comment]
The new `opencollective-postinstall` also doesn't have any dependencies, which is nice. I'm +1 for this.

**Comment by vweevers** [comment]
@ralphtheninja let's merge. In any case we can get this into level 4.0.0. Question is whether we also need to release a patch on 3.x.

**Comment by ralphtheninja** [comment]
> Question is whether we also need to release a patch on 3.x.

Lets do it. Not that much extra work when releasing 4.0.0 anyway.

**Comment by manniL** [comment]
Just in case you want the power of `opencollective-cli postinstall` back, there is a drop-in solution from `nuxt.js` (https://github.com/nuxt-community/opencollective)

**Pull request merged**
