### PR TITLE
types: add typings

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolves https://github.com/Level/level/issues/120

### CODE REVIEW

**Comment by vweevers** [comment]
Typings for Level are maintained in DT.

**Comment by cryptoquick** [comment]
I actually don't see those in DefinitelyTyped.

`yarn add @types/level` returns not found.

**Comment by vweevers** [comment]
@cryptoquick I'll rephrase: typings for projects in the Level org are (or should be) in DT.

**Comment by ethernomad** [comment]
Yeah @types/level doesn't exist. This needs to be created.

**Comment by cryptoquick** [comment]
Yeah, it'd probably be a good idea to make this a priority, given how popular TypeScript is. I was just looking at Level the other day. Does anyone have any other solution for this other than just copying and pasting the files in this PR into your own project? If the devs here aren't taking this as a priority, that's also a problem.

**Comment by vweevers** [comment]
> If the devs here aren't taking this as a priority, that's also a problem.

The devs here are mostly JS users, we don't maintain typings. We tried to, but it quickly became painful and folks from DT recommended that we move the typings there. That move implicitly included the responsibility of maintenance, from us to the community.

Bottom line, if you want a `@types/level` package, please open a pull request to DT. We're happy to answer any JS questions though, for example if you need clarification on the behavior of some specific interface. Good luck!

**Pull request closed without merging**
